root = "."

[[mount]]
alias = "shaders"
path  = "content/shaders"

[[mount]]
alias = "materials"
path  = "content/materials"

[[mount]]
alias = "pipelines"
path  = "content/pipelines"

[[mount]]
alias = "models"
path  = "C:\\Users\\rwf93\\Downloads\\glTF-Sample-Models\\2.0"

[[mount]]
alias = "textures"
path  = "C:\\Users\\rwf93\\Downloads\\glTF-Sample-Models\\2.0"
