# Generated material sidecar for Sponza.gltf.
source = "./Sponza.gltf"
material_roots = ["./materials"]
default_material = "./materials/default_material.toml"

[material_overrides]
"material_0" = "./materials/material_0.toml"
"material_1" = "./materials/material_1.toml"
"material_2" = "./materials/material_2.toml"
"material_3" = "./materials/material_3.toml"
"material_4" = "./materials/material_4.toml"
"material_5" = "./materials/material_5.toml"
"material_6" = "./materials/material_6.toml"
"material_7" = "./materials/material_7.toml"
"material_8" = "./materials/material_8.toml"
"material_9" = "./materials/material_9.toml"
"material_10" = "./materials/material_10.toml"
"material_11" = "./materials/material_11.toml"
"material_12" = "./materials/material_12.toml"
"material_13" = "./materials/material_13.toml"
"material_14" = "./materials/material_14.toml"
"material_15" = "./materials/material_15.toml"
"material_16" = "./materials/material_16.toml"
"material_17" = "./materials/material_17.toml"
"material_18" = "./materials/material_18.toml"
"material_19" = "./materials/material_19.toml"
"material_20" = "./materials/material_20.toml"
"material_21" = "./materials/material_21.toml"
"material_22" = "./materials/material_22.toml"
"material_23" = "./materials/material_23.toml"
"material_24" = "./materials/material_24.toml"
