local gfx_packages = {
    "vulkan-headers",
    "vk-bootstrap",
    "vulkan-memory-allocator",
}

target("gfx")
    set_kind("static")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_defines("VK_NO_PROTOTYPES", {public = true})
    add_includedirs("..", {public = true})
    add_files("*.cpp")
    add_files("texture/*.cpp")
    add_packages(gfx_packages, {public = true})
    add_rules("defaults_rule")

target("gfx_image_io")
    set_kind("static")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_deps("gfx", {public = true})
    add_files("image_io/*.cpp")
    add_packages("stb", "glm")
    add_rules("defaults_rule")

target("gfx_present")
    set_kind("static")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_deps("gfx", {public = true})
    add_files("present/*.cpp")
    add_rules("defaults_rule")

target("gfx_sdl")
    set_kind("static")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_deps("gfx", {public = true})
    add_files("sdl/*.cpp")
    add_packages("libsdl3", {public = true})
    add_rules("defaults_rule")

target("gfx_slang")
    set_kind("static")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_deps("gfx", {public = true})
    add_files("slang/*.cpp")
    add_packages("slang", {public = true})
    add_packages("spdlog")
    add_rules("defaults_rule")

target("gfx_raytracing")
    set_kind("static")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_deps("gfx", "gfx_slang", {public = true})
    add_files("raytracing/*.cpp")
    add_rules("defaults_rule")

target("gfx_framegraph")
    set_kind("static")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_deps("gfx", {public = true})
    add_files("framegraph/*.cpp")
    add_rules("defaults_rule")

target("gfx_imgui")
    set_kind("static")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_deps("gfx", "gfx_sdl", {public = true})
    add_files("imgui/imgui.cpp")
    add_files("imgui/imgui_*.cpp")
    add_files("imgui/backends/imgui_impl_vulkan.cpp")
    add_files("imgui/backends/imgui_impl_sdl3.cpp")
    add_files("imgui/imguizmo/*.cpp")
    add_includedirs("imgui", {public = true})
    add_includedirs("imgui/backends", {public = true})
    add_includedirs("imgui/imguizmo", {public = true})
    add_rules("defaults_rule")

target("gfx_compute_example")
    set_kind("binary")
    set_group("examples")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_deps("gfx", "gfx_slang")
    add_files("examples/compute.cpp")
    add_rules("defaults_rule")

target("gfx_raytracing_example")
    set_kind("binary")
    set_group("examples")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_deps("gfx", "gfx_slang", "gfx_raytracing", "gfx_present", "gfx_sdl", "gfx_framegraph")
    add_files("examples/raytracing.cpp")
    add_rules("defaults_rule")

target("gfx_triangle_example")
    set_kind("binary")
    set_group("examples")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_deps("gfx", "gfx_slang", "gfx_present", "gfx_sdl")
    add_files("examples/triangle.cpp")
    add_rules("defaults_rule")

target("gfx_triangle_framegraph_example")
    set_kind("binary")
    set_group("examples")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_deps("gfx", "gfx_slang", "gfx_present", "gfx_sdl", "gfx_framegraph")
    add_files("examples/triangle_framegraph.cpp")
    add_rules("defaults_rule")

target("gfx_ttf_framegraph_example")
    set_kind("binary")
    set_group("examples")
    set_languages("cxx26")
    set_encodings("utf-8")
    add_deps("gfx", "gfx_slang", "gfx_present", "gfx_sdl", "gfx_framegraph")
    add_files("examples/ttf_framegraph.cpp")
    add_rules("defaults_rule")
